"""Named, managed tmux sessions: create-or-reuse by name, drive by sid"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_bg.ipynb.

# %% auto #0
__all__ = ['SESSION_PREFIX', 'start_session', 'pane', 'send', 'send_keys', 'interrupt', 'poll', 'display', 'close',
           'managed_sessions']

# %% ../nbs/01_bg.ipynb #fd3e271a
from fastcore.utils import *
from .core import *
from .core import _tmux
import uuid

# %% ../nbs/01_bg.ipynb #ff5a0a57
SESSION_PREFIX = 'fastmux-'

def start_session(
    sid=None,    # Session name; default: a generated `fastmux-`-prefixed name
    cmd=None,    # Command to run (str or argv list); default: the user's shell
    cwd=None,    # Working directory
    env=None,    # Extra environment vars as a dict
    width=None,  # Terminal width in columns
    height=None, # Terminal height in rows
):
    "The session named `sid`, created detached (managed, with `remain` set) if it doesn't exist"
    if sid is None: sid = f'{SESSION_PREFIX}{uuid.uuid4().hex[:10]}'
    try: return tmux(sid)
    except TmuxError: pass
    s = new_session(name=sid, width=width, height=height, cwd=cwd, env=env, remain=True)
    p = Pane.fetch(s.id)
    _tmux('set-option','-t',s.id,'@fastmux_pane_id',p.id)
    _tmux('set-option','-w','-t',p.id,'remain-on-exit-format','')
    if cmd is not None:
        args = ['respawn-pane','-k','-t',p.id]
        if cwd is not None: args += ['-c',os.fspath(cwd)]
        args += [x for k,v in (env or {}).items() for x in ('-e',f'{k}={v}')]
        args += [cmd] if isinstance(cmd,str) else list(cmd)
        _tmux(*args)
    return s

# %% ../nbs/01_bg.ipynb #25b4280b
def pane(sid=None):
    "The pane `sid` addresses: a session name (its managed pane), a `%pane_id`, a `Session` or `Pane` handle, or None for the current pane"
    if isinstance(sid, Pane): return sid
    if isinstance(sid, Session): sid = sid.name
    if sid is None: return current_pane()
    if sid.startswith('%'): return Pane.fetch(sid)
    _tmux('has-session','-t',f'={sid}')
    pid = _tmux('show-options','-qv','-t',sid,'@fastmux_pane_id')
    return Pane.fetch(pid or sid)

# %% ../nbs/01_bg.ipynb #26bfe98f
def send(sid=None, chars='', wait_ms=0, interval_ms=50, lines=80):
    "Paste `chars` into `sid`'s pane literally, then `poll`"
    return pane(sid).send(chars, wait_ms, interval_ms, lines)

def send_keys(sid=None, *keys, wait_ms=0, interval_ms=50, lines=80):
    "Send tmux key names to `sid`'s pane, then `poll`"
    return pane(sid).send_keys(*keys, wait_ms=wait_ms, interval_ms=interval_ms, lines=lines)

def interrupt(sid=None, wait_ms=0, interval_ms=50, lines=80):
    "Send `Ctrl-C` to `sid`'s pane, then `poll`"
    return pane(sid).interrupt(wait_ms, interval_ms, lines)

def poll(sid=None, wait_ms=0, interval_ms=50, lines=80):
    "Wait for `sid`'s pane to differ from its last-seen state, then capture the last `lines`"
    return pane(sid).poll(wait_ms, interval_ms, lines)

def display(sid=None, lines=80):
    "Capture the last `lines` of `sid`'s pane"
    return pane(sid).display(lines)

# %% ../nbs/01_bg.ipynb #f723b963
def close(sid=None):
    "Kill the session owning `sid`'s pane"
    Session.fetch(pane(sid).session).kill()

def managed_sessions():
    "Sessions created by `start_session`"
    return Sessions(s for s in tmux() if _tmux('show-options','-qv','-t',s.id,'@fastmux_pane_id'))
