"""Drive and inspect tmux from Python: live session, window, and pane handles with CLI-style reprs"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['SEARCH_LINES', 'TmuxError', 'Session', 'new_session', 'Pane', 'Capture', 'Panes', 'Window', 'Windows', 'SearchMatch',
           'SearchResults', 'Sessions', 'tmux']

# %% ../nbs/00_core.ipynb #9cc1145d
from fastcore.utils import *
from fastcore.meta import delegates

import re, shlex, socket, subprocess, sys, time, uuid

# %% ../nbs/00_core.ipynb #f490b9ef
class TmuxError(RuntimeError):
    "Raised when a tmux command fails or a target cannot be resolved."

def _tmux(*args: str, input: str | None = None):
    proc = subprocess.run(["tmux", *args], input=input, text=True, capture_output=True, check=False)
    if proc.returncode != 0:
        stderr = proc.stderr.strip() or proc.stdout.strip()
        raise TmuxError(stderr or f"tmux command failed: {args!r}")
    return proc.stdout.rstrip("\n")

# %% ../nbs/00_core.ipynb #daaec622
_sess_f = dict(id='session_id', name='session_name', n_wins='session_windows', attached='session_attached')
_win_f  = dict(id='window_id', session='session_name', idx='window_index', name='window_name', active='window_active', n_panes='window_panes')
_pane_f = dict(id='pane_id', session='session_name', window_id='window_id', win='window_index', idx='pane_index',
    cmd='pane_current_command', active='pane_active', dead='pane_dead', width='pane_width', height='pane_height',
    hist='history_size', cy='cursor_y', dead_status='pane_dead_status', title='pane_title')
_ints  = {'win','idx','width','height','hist','cy','n_wins','n_panes'}
_bools = {'active','dead','attached'}

def _fmt(fields): return '\t'.join(f'#{{{v}}}' for v in fields.values())

def _parse(fields, line):
    d = dict(zip(fields, line.split('\t', len(fields)-1)))
    for k in fields.keys() & _ints: d[k] = int(d[k])
    for k in fields.keys() & _bools: d[k] = d[k]=='1'
    return d

def _get(fields, target): return _parse(fields, _tmux('display-message','-p','-t',str(target),_fmt(fields)))
def _list(cmd, fields, *flags): return [_parse(fields, l) for l in _tmux(cmd,*flags,'-F',_fmt(fields)).splitlines()]

# %% ../nbs/00_core.ipynb #cde73486
class Session(AttrDict):
    "A tmux session; fields from `_sess_f`, keyed on the immutable session id"
    @classmethod
    def fetch(cls, target): return cls(_get(_sess_f, target))
    def refresh(self):
        self.update(_get(_sess_f, self.id))
        return self
    def __repr__(self): return f"{self.name}: {self.n_wins} windows{' (attached)' if self.attached else ''}"
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

def new_session(
    cmd=None,     # Command to run (str or argv list); default: the user's shell
    name=None,    # Session name; default: tmux auto-numbers
    width=None,   # Terminal width in columns
    height=None,  # Terminal height in rows
    cwd=None,     # Working directory
    env=None,     # Extra environment vars as a dict
    remain=False, # Keep dead panes around (inspectable, with exit status) instead of destroying them
):
    "Start a detached tmux session and return its `Session`"
    args = ['new-session','-d','-P','-F','#{session_id}']
    if name: args += ['-s',name]
    if width: args += ['-x',str(width)]
    if height: args += ['-y',str(height)]
    if cwd: args += ['-c',str(cwd)]
    for k,v in (env or {}).items(): args += ['-e',f'{k}={v}']
    if cmd: args += [cmd] if isinstance(cmd,str) else list(cmd)
    sid = _tmux(*args)
    if remain: _tmux('set-option','-w','-t',sid,'remain-on-exit','on')
    return Session.fetch(sid)

# %% ../nbs/00_core.ipynb #09317d38
@patch
def kill(self:Session):
    "Kill this session and everything in it"
    sys.audit('fastmux.Session.kill', self.id)
    _tmux('kill-session','-t',self.id)

@patch
def rename(self:Session, name):
    "Rename this session, returning it"
    _tmux('rename-session','-t',self.id,name)
    return self.refresh()

@patch(as_prop=True)
def attach_command(self:Session):
    "Shell command that attaches a terminal to this session"
    return f'tmux attach -t {shlex.quote(self.name)}'

# %% ../nbs/00_core.ipynb #cfb08433
class Pane(AttrDict):
    "A tmux pane; fields from `_pane_f`, keyed on the immutable pane id"
    @classmethod
    def fetch(cls, target): return cls(_get(_pane_f, target))
    def refresh(self):
        self.update(_get(_pane_f, self.id))
        return self
    @property
    def target(self): return f'{self.session}:{self.win}.{self.idx}'
    @property
    def running(self): return not self.dead
    @property
    def exit_code(self): return int(self.dead_status) if self.dead and self.dead_status else None

# %% ../nbs/00_core.ipynb #bd3b4e02
def _nlines(p):
    "Transcript line count up to the cursor, ignoring a trailing blank cursor row"
    n = p.hist + p.cy + 1
    if n <= 0: return 0
    return n-1 if _tmux('capture-pane','-p','-t',p.id,'-S',str(p.cy),'-E',str(p.cy))=='' else n

class Capture(AttrDict):
    "Captured transcript lines plus their absolute range and source pane"
    def __repr__(self):
        status = '' if self.running else (f' · exited {self.exit_code}' if self.exit_code is not None else ' · dead')
        src = f'── {self.target} {self.id} · lines {self.start}-{self.end} of {self.n}{status}'
        return f'{self.text}\n{src}' if self.text else src
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

@patch
def capture(self:Pane, start=0, end=None, ansi=False):
    "A `Capture` of transcript lines `start:end` (absolute; `end=None` means up to the cursor)"
    self.refresh()
    n = _nlines(self)
    if end is None: end = n
    start, end = max(0,min(start,n)), max(0,min(end,n))
    if start >= end: text = ''
    else: text = _tmux( 'capture-pane','-p',*(['-e'] if ansi else []),'-t',self.id,
                        '-S',str(start-self.hist),'-E',str(end-self.hist-1))
    return Capture(text=text, lines=tuple(text.splitlines()), start=start, end=end, n=n,
                   target=self.target, id=self.id, running=self.running, exit_code=self.exit_code)

# %% ../nbs/00_core.ipynb #7ecd63ca
@patch(as_prop=True)
def text(self:Pane):
    "The visible screen as plain text"
    return _tmux('capture-pane','-p','-t',self.id)

@patch(as_prop=True)
def ansi(self:Pane):
    "The visible screen with ANSI escape sequences"
    return _tmux('capture-pane','-p','-e','-t',self.id)

@patch
def __repr__(self:Pane):
    try: return self.text
    except TmuxError: return f"Pane({self['id']} gone)"

@patch
def _repr_pretty_(self:Pane, pr, cycle): pr.text(repr(self))

# %% ../nbs/00_core.ipynb #c3c3ebca
@patch
def __len__(self:Pane): return _nlines(self.refresh())

@patch
def __getitem__(self:Pane, i):
    "Transcript line `i` as a str, a `Capture` for a slice; str keys keep normal dict access"
    if isinstance(i, str): return dict.__getitem__(self, i)
    n = len(self)
    if isinstance(i, slice):
        start, end, step = i.indices(n)
        if step != 1: raise ValueError('step slicing not supported')
        return self.capture(start, end)
    if i < 0: i += n
    if not 0 <= i < n: raise IndexError(i)
    return self.capture(i, i+1).text

@patch
def display(self:Pane, lines=80, ansi=False):
    "Capture the last `lines` transcript lines"
    n = _nlines(self.refresh())
    return self.capture(max(0, n-lines), ansi=ansi)

# %% ../nbs/00_core.ipynb #0e1ce944
def _snapshot(p, lines):
    c = p.display(lines)
    return c.text, c.n, c.running, c.exit_code

@patch
def poll(self:Pane, wait_ms=0, interval_ms=50, lines=80):
    "Wait up to `wait_ms` for visible change (returning early if it comes), then capture the last `lines`"
    if wait_ms > 0:
        base = _snapshot(self, lines)
        deadline = time.monotonic() + wait_ms/1000
        while time.monotonic() < deadline:
            time.sleep(min(interval_ms/1000, max(0, deadline-time.monotonic())))
            if _snapshot(self, lines) != base: break
    return self.display(lines)

# %% ../nbs/00_core.ipynb #b429cbcd
@patch
def send(self:Pane, chars='', wait_ms=0, interval_ms=50, lines=80):
    "Paste `chars` into this pane literally, then `poll`"
    if chars:
        buf = f'fastmux-{uuid.uuid4().hex}'
        _tmux('load-buffer','-b',buf,'-',input=chars)
        try: _tmux('paste-buffer','-d','-b',buf,'-t',self.id)
        except Exception:
            try: _tmux('delete-buffer','-b',buf)
            except TmuxError: pass
            raise
    return self.poll(wait_ms, interval_ms, lines)

@patch
def send_keys(self:Pane, *keys, wait_ms=0, interval_ms=50, lines=80):
    "Send tmux key names to this pane, then `poll`"
    if keys: _tmux('send-keys','-t',self.id,*keys)
    return self.poll(wait_ms, interval_ms, lines)

@patch
def interrupt(self:Pane, wait_ms=0, interval_ms=50, lines=80):
    "Send `Ctrl-C` to this pane, then `poll`"
    return self.send_keys('C-c', wait_ms=wait_ms, interval_ms=interval_ms, lines=lines)

@patch
def wait(self:Pane, timeout_ms=None, interval_ms=50):
    "Wait for this pane's command to exit, returning its status (`None` on timeout)"
    deadline = None if timeout_ms is None else time.monotonic() + max(timeout_ms,0)/1000
    while True:
        self.refresh()
        if self.dead: return self.exit_code
        if deadline is not None and time.monotonic() >= deadline: return None
        time.sleep(interval_ms/1000)

# %% ../nbs/00_core.ipynb #fc2cd8fc
def _pane_row(p):
    tag = ('' if not p.active else ' (active)') + ('' if not p.dead else ' (dead)')
    title = f' · {p.title}' if p.title and p.title != p.cmd and p.title != socket.gethostname() else ''
    return f'{p.win}.{p.idx}: [{p.width}x{p.height}] {p.id} {p.cmd}{tag}{title}'

class Panes(L):
    "Panes shown as `tmux list-panes`-style summary lines"
    def __repr__(self): return '\n'.join(_pane_row(o) for o in self)
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

@patch(as_prop=True)
def panes(self:Session):
    "All panes in this session"
    return Panes(Pane(d) for d in _list('list-panes', _pane_f, '-s','-t',self.id))

@patch(as_prop=True)
def pane(self:Session):
    "This session's active pane"
    return Pane.fetch(self.id)

# %% ../nbs/00_core.ipynb #84fdf567
class Window(AttrDict):
    "A tmux window; fields from `_win_f`, keyed on the immutable window id"
    @classmethod
    def fetch(cls, target): return cls(_get(_win_f, target))
    def refresh(self):
        self.update(_get(_win_f, self.id))
        return self
    @property
    def panes(self): return Panes(Pane(d) for d in _list('list-panes', _pane_f, '-t',self.id))
    def __repr__(self):
        head = f"{self.idx}: {self.name}{'*' if self.active else ''} ({self.n_panes} panes) {self.id}"
        return '\n'.join([head] + [f'  {_pane_row(o)}' for o in self.panes])
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

class Windows(L):
    "Windows shown with their pane listings"
    def __repr__(self): return '\n'.join(repr(o) for o in self)
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

@patch(as_prop=True)
def windows(self:Session):
    "This session's windows"
    return Windows(Window(d) for d in _list('list-windows', _win_f, '-t',self.id))

@patch
def new_window(
    self:Session,
    cmd=None,     # Command to run (str or argv list); default: the user's shell
    name=None,    # Window name; default: tmux auto-names from the command
    cwd=None,     # Working directory
    env=None,     # Extra environment vars as a dict
    remain=False, # Keep dead panes around instead of destroying them
    focus=False,  # Make it the session's current window
):
    "Create a window in this session, returning the new `Window`"
    args = ['new-window','-P','-F','#{window_id}','-t',self.id]
    if not focus: args += ['-d']
    if name: args += ['-n',name]
    if cwd: args += ['-c',str(cwd)]
    for k,v in (env or {}).items(): args += ['-e',f'{k}={v}']
    if cmd: args += [cmd] if isinstance(cmd,str) else list(cmd)
    wid = _tmux(*args)
    if remain: _tmux('set-option','-w','-t',wid,'remain-on-exit','on')
    return Window.fetch(wid)

# %% ../nbs/00_core.ipynb #94808aa5
@patch
def kill(self:Window):
    "Kill this window and its panes"
    sys.audit('fastmux.Window.kill', self.id)
    _tmux('kill-window','-t',self.id)

@patch
def rename(self:Window, name):
    "Rename this window, returning it"
    _tmux('rename-window','-t',self.id,name)
    return self.refresh()

@patch
def select(self:Window):
    "Make this the session's current window, returning it"
    _tmux('select-window','-t',self.id)
    return self.refresh()

@patch
def layout(self:Window, name):
    "Apply a tmux layout (`even-horizontal`, `tiled`, ...), returning this window"
    _tmux('select-layout','-t',self.id,name)
    return self.refresh()

# %% ../nbs/00_core.ipynb #a25490e7
_split_flags = dict(right=['-h'], below=['-v'], left=['-h','-b'], above=['-v','-b'])

@patch
def split(
    self:Pane,
    where='right', # Where the new pane goes: `right`, `below`, `left`, or `above`
    cmd=None,      # Command to run (str or argv list); default: the user's shell
    size=None,     # Size of the new pane: rows/columns (int) or `'30%'`
    cwd=None,      # Working directory
    env=None,      # Extra environment vars as a dict
    focus=False,   # Make the new pane active
):
    "Split this pane, returning the new `Pane`"
    args = ['split-window','-P','-F','#{pane_id}',*_split_flags[where],'-t',self.id]
    if not focus: args += ['-d']
    if size: args += ['-l',str(size)]
    if cwd: args += ['-c',str(cwd)]
    for k,v in (env or {}).items(): args += ['-e',f'{k}={v}']
    if cmd: args += [cmd] if isinstance(cmd,str) else list(cmd)
    return Pane.fetch(_tmux(*args))

@patch
@delegates(Pane.split)
def rsplit(self:Pane, **kwargs): return self.split('right', **kwargs)
@patch
@delegates(Pane.split)
def bsplit(self:Pane, **kwargs): return self.split('below', **kwargs)
@patch
@delegates(Pane.split)
def lsplit(self:Pane, **kwargs): return self.split('left', **kwargs)
@patch
@delegates(Pane.split)
def asplit(self:Pane, **kwargs): return self.split('above', **kwargs)

# %% ../nbs/00_core.ipynb #8a009431
@patch
def kill(self:Pane):
    "Kill this pane (killing its window/session if it is the last one)"
    sys.audit('fastmux.Pane.kill', self.id)
    _tmux('kill-pane','-t',self.id)

@patch
def resize(self:Pane, width=None, height=None):
    "Resize this pane to absolute `width`/`height`, returning it"
    args = ['resize-pane','-t',self.id]
    if width: args += ['-x',str(width)]
    if height: args += ['-y',str(height)]
    _tmux(*args)
    return self.refresh()

@patch
def zoom(self:Pane):
    "Toggle this pane fullscreen within its window, returning it"
    _tmux('resize-pane','-Z','-t',self.id)
    return self.refresh()

@patch
def select(self:Pane):
    "Make this the active pane, returning it"
    _tmux('select-pane','-t',self.id)
    return self.refresh()

# %% ../nbs/00_core.ipynb #c0a60628
SEARCH_LINES = 2000

class SearchMatch(AttrDict):
    "One matching transcript line, shown rg-style"
    def __repr__(self): return f'{self.target}:{self.line_no}: {self.line}'
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

class SearchResults(L):
    "Search matches, one rg-style row per line"
    def __repr__(self): return '\n'.join(repr(o) for o in self)
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

def _matcher(pattern, regex=False, ignore_case=True):
    if regex: return re.compile(pattern, re.IGNORECASE if ignore_case else 0).search
    if ignore_case:
        pattern = pattern.lower()
        return lambda l: pattern in l.lower()
    return lambda l: pattern in l

def _search_panes(ps, pattern, lines=SEARCH_LINES, regex=False, ignore_case=True):
    f = _matcher(pattern, regex, ignore_case)
    return SearchResults(SearchMatch(target=c.target, line_no=c.start+i, line=l, id=c.id)
        for c in (p.display(lines) for p in ps) for i,l in enumerate(c.lines) if f(l))

@patch
def search(self:Pane, pattern, lines=SEARCH_LINES, regex=False, ignore_case=True):
    "Search this pane's recent transcript, rg-style"
    return _search_panes([self], pattern, lines, regex, ignore_case)

@patch
def search(self:Window, pattern, lines=SEARCH_LINES, regex=False, ignore_case=True):
    "Search every pane in this window, rg-style"
    return _search_panes(self.panes, pattern, lines, regex, ignore_case)

@patch
def search(self:Session, pattern, lines=SEARCH_LINES, regex=False, ignore_case=True):
    "Search every pane in this session, rg-style"
    return _search_panes(self.panes, pattern, lines, regex, ignore_case)

# %% ../nbs/00_core.ipynb #387659f2
class Sessions(L):
    "Sessions shown as an indented session/window/pane tree"
    def __repr__(self):
        def _ind(o): return '\n'.join(f'  {l}' for l in repr(o).splitlines())
        return '\n'.join('\n'.join([repr(o)] + [_ind(w) for w in o.windows]) for o in self)
    def _repr_pretty_(self, p, cycle): p.text(repr(self))

    def search(self, pattern, lines=SEARCH_LINES, regex=False, ignore_case=True):
        "Search every pane in every session, rg-style"
        return _search_panes([Pane(d) for d in _list('list-panes', _pane_f, '-a')], pattern, lines, regex, ignore_case)

def tmux(target=None):
    "All sessions as a tree, or a live handle for `target` (session name, `sess:win`, `sess:win.pane`, or a `$`/`@`/`%` id)"
    if target is None: return Sessions(Session(d) for d in _list('list-sessions', _sess_f))
    t = str(target)
    if t.startswith('$'): return Session.fetch(t)
    if t.startswith('@') or (':' in t and '.' not in t): return Window.fetch(_tmux('display-message','-p','-t',t,'#{window_id}'))
    if t.startswith('%') or ':' in t or '.' in t: return Pane.fetch(_tmux('display-message','-p','-t',t,'#{pane_id}'))
    _tmux('has-session','-t',f'={t}')  # exact-name existence check
    return Session.fetch(t)
